#!/usr/bin/env bash
#
# bootstrap.sh — one-command production bring-up for a fresh server.
#
#   git clone git@github.com:iamsoroush/engram.git /srv/engram
#   cd /srv/engram
#   ./scripts/bootstrap.sh                      # interactive: prompts for the gateway API key
#   # or fully non-interactive:
#   GATEWAY_API_KEY=gw_xxx ./scripts/bootstrap.sh
#
#   # move a server / disaster recovery — reuse the SAME secrets, then restore the latest dump:
#   scp OLD_HOST:/srv/engram/.env.prod .                        # same secrets (esp. BACKUP_ENCRYPTION_KEY)
#   scp OLD_HOST:/var/backups/engram/pg-LATEST.sql.gz.enc /tmp/
#   RESTORE_FROM=/tmp/pg-LATEST.sql.gz.enc ./scripts/bootstrap.sh
#
# What it does (idempotent + safe):
#   1. Checks prerequisites (docker, docker compose, openssl).
#   2. Ensures swap on small boxes (the frontend build is the RAM spike → OOM without it).
#   3. Creates .env.prod IF MISSING — generates strong secrets + fills the engram/gateway
#      defaults and wires the DB password into BACKEND_DATABASE_URL. It NEVER overwrites an
#      existing .env.prod, so MOVING A SERVER while keeping data = scp the old .env.prod over
#      first, then run this (it reuses the same secrets, so a restored backup still decrypts).
#   4. Runs scripts/deploy.sh (build + migrate + start TLS stack + health-check).
#   5. RESTORE: if RESTORE_FROM is set, stops the app, restores that dump, restarts (the backend
#      re-applies any newer migrations on start). Needs the same BACKUP_ENCRYPTION_KEY as the dump.
#   6. BACKUP: schedules a nightly encrypted Postgres backup (scripts/backup.sh) via cron.
#
# Tunables (env vars; all have sane defaults except the API key):
#   DOMAIN           default engram.ir              GATEWAY_MODEL    default gemini-3.1-flash-lite
#   GATEWAY_URL      default https://gw.engram.ir/v1 SYNTHESIS_MODEL default gpt-5.4-mini
#   GATEWAY_API_KEY  required when creating a fresh .env.prod (prompted if unset)
#   SETUP_SWAP       default auto (set 0 to skip)    RESTORE_FROM     path to a dump to restore (optional)
#   BACKUP_AT        cron time for nightly backup (default "0 2 * * *");  SETUP_BACKUP_CRON=0 to skip
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
ENV_FILE="$REPO_ROOT/.env.prod"

DOMAIN="${DOMAIN:-engram.ir}"
GATEWAY_URL="${GATEWAY_URL:-https://gw.engram.ir/v1}"
GATEWAY_MODEL="${GATEWAY_MODEL:-gemini-3.1-flash-lite}"
SYNTHESIS_MODEL="${SYNTHESIS_MODEL:-gpt-5.4-mini}"

SUDO=""; [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null && SUDO="sudo"
log()  { printf '\n\033[1;36m[bootstrap]\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31m[bootstrap] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. prerequisites --------------------------------------------------------------------------
log "checking prerequisites"
command -v docker >/dev/null || die "docker not found. Install Docker Engine + the compose plugin: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "'docker compose' plugin not found (install docker-compose-plugin)."
command -v openssl >/dev/null || die "openssl not found."

# --- 2. swap (small boxes OOM during the frontend Vite build) ----------------------------------
if [ "${SETUP_SWAP:-auto}" != "0" ] && [ -r /proc/meminfo ]; then
  mem_kb=$(awk '/MemTotal/{print $2}' /proc/meminfo)
  swap_kb=$(awk '/SwapTotal/{print $2}' /proc/meminfo)
  if [ "${mem_kb:-0}" -lt 3145728 ] && [ "${swap_kb:-0}" -lt 1048576 ]; then
    log "low RAM ($((mem_kb/1024)) MB) and little/no swap — creating a 4G swapfile"
    $SUDO fallocate -l 4G /swapfile 2>/dev/null || $SUDO dd if=/dev/zero of=/swapfile bs=1M count=4096
    $SUDO chmod 600 /swapfile
    $SUDO mkswap /swapfile >/dev/null
    $SUDO swapon /swapfile
    grep -q '/swapfile' /etc/fstab 2>/dev/null || echo '/swapfile none swap sw 0 0' | $SUDO tee -a /etc/fstab >/dev/null
  fi
fi

# --- 3. .env.prod ------------------------------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  log ".env.prod already exists — reusing it (secrets NOT regenerated)."
else
  log "no .env.prod — creating one with fresh secrets"
  if [ -z "${GATEWAY_API_KEY:-}" ]; then
    read -rsp "AI gateway API key (AI_ENGINE_TRANSCRIPTION_API_KEY): " GATEWAY_API_KEY; echo
  fi
  [ -n "${GATEWAY_API_KEY:-}" ] || die "GATEWAY_API_KEY is required to create a fresh .env.prod."

  safe() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | cut -c1-"${1:-40}"; }
  PG_PASS="$(safe 40)"; MINIO_PASS="$(safe 40)"; MINIO_USER="engram-prod"
  JWT_SECRET="$(openssl rand -hex 48)"; INTERNAL_TOKEN="$(openssl rand -hex 32)"; BACKUP_KEY="$(safe 48)"

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap.sh — DO NOT COMMIT. Secrets are unique to this server;
# back them up (esp. BACKUP_ENCRYPTION_KEY) and reuse this file to move servers without data loss.
CADDY_SITE_ADDRESS=$DOMAIN
PROD_FRONTEND_PORT=127.0.0.1:8080
PROD_VITE_API_URL=

POSTGRES_DB=engram
POSTGRES_USER=engram
POSTGRES_PASSWORD=$PG_PASS
MINIO_ROOT_USER=$MINIO_USER
MINIO_ROOT_PASSWORD=$MINIO_PASS
BACKEND_JWT_SECRET=$JWT_SECRET
AI_ENGINE_INTERNAL_TOKEN=$INTERNAL_TOKEN

BACKEND_APP_NAME=Engram API
BACKEND_AUTH_MODE=production
BACKEND_CORS_ORIGINS=["https://$DOMAIN"]
BACKEND_DATABASE_URL=postgresql+psycopg://engram:$PG_PASS@postgres:5432/engram

BACKEND_OBJECT_STORAGE_ENDPOINT=http://minio:9000
BACKEND_OBJECT_STORAGE_PUBLIC_ENDPOINT=
BACKEND_OBJECT_STORAGE_BUCKET=engram-captures
# Demo: backend uses the MinIO root key. Create an app-scoped key before real clinical data.
BACKEND_OBJECT_STORAGE_ACCESS_KEY=$MINIO_USER
BACKEND_OBJECT_STORAGE_SECRET_KEY=$MINIO_PASS
BACKEND_OBJECT_STORAGE_SECURE=false
BACKEND_OBJECT_STORAGE_PRESIGNED_URL_TTL_SECONDS=300

BACKEND_CELERY_BROKER_URL=redis://redis:6379/0
BACKEND_CELERY_RESULT_BACKEND=redis://redis:6379/1
BACKEND_AI_JOB_MAX_RETRIES=3
BACKEND_AI_JOB_RETRY_DELAY_SECONDS=30

AI_ENGINE_BACKEND_INTERNAL_URL=http://backend:8000
AI_ENGINE_TRANSCRIPTION_BASE_URL=$GATEWAY_URL
AI_ENGINE_TRANSCRIPTION_API_KEY=$GATEWAY_API_KEY
AI_ENGINE_TRANSCRIPTION_MODEL=$GATEWAY_MODEL

BACKEND_REPORT_SYNTHESIS_ENABLED=true
AI_ENGINE_REPORT_SYNTHESIS_MODEL=$SYNTHESIS_MODEL
AI_ENGINE_REPORT_SYNTHESIS_REASONING_EFFORT=low
AI_ENGINE_CAPTION_MODEL=
AI_ENGINE_PATIENT_MEMORY_MODEL=

BACKUP_DIR=/var/backups/engram
BACKUP_RETAIN_DAYS=14
BACKUP_ENCRYPTION_KEY=$BACKUP_KEY
OFFSITE_ALIAS=
OFFSITE_BUCKET=engram-backups
EOF
  chmod 600 "$ENV_FILE"
  log ".env.prod created (chmod 600). BACK UP ITS SECRETS — lose BACKUP_ENCRYPTION_KEY and encrypted backups are unrecoverable."
fi

# --- 4. pre-deploy reminder + best-effort DNS sanity -------------------------------------------
log "reminder: '$DOMAIN' must already resolve to THIS server (A record, DNS-only) and ports 80/443 must be open, or Caddy can't get a TLS cert."
if command -v dig >/dev/null; then
  resolved="$(dig +short "$DOMAIN" | tail -n1 || true)"
  here="$(curl -fsS -m 5 https://api.ipify.org 2>/dev/null || true)"
  if [ -n "$resolved" ] && [ -n "$here" ] && [ "$resolved" != "$here" ]; then
    log "WARNING: $DOMAIN resolves to '$resolved' but this host looks like '$here'. Cert issuance may fail until DNS matches."
  fi
fi

# --- 5. deploy ---------------------------------------------------------------------------------
log "deploying (build + migrate + TLS stack + health-check)"
"$REPO_ROOT/scripts/deploy.sh"

COMPOSE="docker compose -f docker-compose.prod.yml -f docker-compose.prod.tls.yml --env-file .env.prod"

# --- 6. optional restore (moving a server / disaster recovery) ---------------------------------
if [ -n "${RESTORE_FROM:-}" ]; then
  [ -f "$RESTORE_FROM" ] || die "RESTORE_FROM='$RESTORE_FROM' not found on disk."
  log "restoring database from $RESTORE_FROM (stopping app containers during the load)"
  $COMPOSE stop backend ai-engine >/dev/null
  printf 'yes\n' | "$REPO_ROOT/scripts/restore.sh" "$RESTORE_FROM"
  log "restarting app — the backend re-applies any newer migrations on the restored DB"
  $COMPOSE up -d backend ai-engine >/dev/null
  log "NOTE: database restored. Object-storage MEDIA is restored separately from your off-box"
  log "      mirror, e.g.:  mc mirror \${OFFSITE_ALIAS}/\${OFFSITE_BUCKET}/media local/engram-captures"
fi

# --- 7. schedule nightly backups (idempotent) --------------------------------------------------
if [ "${SETUP_BACKUP_CRON:-1}" != "0" ]; then
  BACKUP_CRON="${BACKUP_AT:-0 2 * * *} cd $REPO_ROOT && $REPO_ROOT/scripts/backup.sh >> /var/log/engram-backup.log 2>&1"
  if $SUDO crontab -l 2>/dev/null | grep -qF "$REPO_ROOT/scripts/backup.sh"; then
    log "nightly backup cron already installed"
  else
    { $SUDO crontab -l 2>/dev/null || true; echo "$BACKUP_CRON"; } | $SUDO crontab -
    $SUDO touch /var/log/engram-backup.log 2>/dev/null || true
    log "installed nightly backup cron -> scripts/backup.sh (log: /var/log/engram-backup.log)"
  fi
  if ! grep -q '^OFFSITE_ALIAS=.\+' "$ENV_FILE" 2>/dev/null; then
    log "backups are LOCAL-ONLY (die with the box). For off-box durability set OFFSITE_ALIAS in"
    log "      .env.prod + configure 'mc' to ArvanCloud S3 — see docs/production.md (Backups & restore)."
  fi
fi

log "bootstrap complete. Verify externally:  curl -I https://$DOMAIN/api/v1/health"
